use_frameworks!

target 'ReduxCounterExample' do
  pod 'Redux.swift/RxSwift', :path => '../'
  pod 'RxCocoa'
end

target 'Redux.swift_Tests' do
  pod 'Redux.swift/RxSwift', :path => '../'
  pod 'Nimble', '~> 3.0'
end
