use_frameworks!

target 'ReduxCounterExample' do
  pod 'Redux.swift', :path => '../'
end

target 'Redux.swift_Tests' do
  pod 'Redux.swift', :path => '../'
  pod 'Nimble', '~> 5.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
