use_frameworks!

target 'ReduxCounterExample' do
  pod 'Redux.swift', :path => '../'
end

target 'Redux.swift_Tests' do
  pod 'Redux.swift', :path => '../'
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
